In [1]:
import pandas as pd

In [45]:
crime_report = pd.read_csv('crime_report.csv')

In [46]:
rent_2012 = pd.read_csv('Area_12.csv')

In [47]:
crime_report = crime_report[crime_report['agency_jurisdiction'].notna()]

In [50]:
list_of_cities = crime_report.agency_jurisdiction.unique()
list_of_cities

array(['Albuquerque, NM', 'Arlington, TX', 'Atlanta, GA', 'Aurora, CO',
       'Austin, TX', 'Baltimore, MD', 'Boston, MA', 'Buffalo, NY',
       'Charlotte, NC', 'Chicago, IL', 'Cincinnati, OH', 'Cleveland, OH',
       'Columbus, OH', 'Dallas, TX', 'Denver, CO', 'Detroit, MI',
       'El Paso, TX', 'Fort Worth, TX', 'Fresno, CA', 'Honolulu, HI',
       'Houston, TX', 'Indianapolis, IN', 'Jacksonville, FL',
       'Kansas City, MO', 'Las Vegas, NV', 'Long Beach, CA',
       'Los Angeles, CA', 'Louisville, KY', 'Memphis, TN', 'Mesa, AZ',
       'Miami, FL', 'Milwaukee, WI', 'Minneapolis, MN', 'Nashville, TN',
       'New Orleans, LA', 'New York, NY', 'Newark, NJ', 'Oakland, CA',
       'Oklahoma City, OK', 'Omaha, NE', 'Orlando, FL',
       'Philadelphia, PA', 'Phoenix, AZ', 'Pittsburgh, PA',
       'Portland, OR', 'Raleigh, NC', 'Sacramento, CA',
       'Salt Lake City, UT', 'San Antonio, TX', 'San Diego, CA',
       'San Francisco, CA', 'San Jose, CA', 'Seattle, WA',
       'St. Louis, MO', 'Tampa, FL', 'Tucson, AZ', 'Tulsa, OK',
       'Virginia Beach, VA', 'Washington, DC', 'Wichita, KS'],
      dtype=object)

In [58]:
states=[]
for i in range(len(list_of_cities)):
    size = len(list_of_cities[i])
    states.append(list_of_cities[i][size-2:])
    
states= states*11

['NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS',
 'NM',
 'TX',
 'GA',
 'CO',
 'TX',
 'MD',
 'MA',
 'NY',
 'NC',
 'IL',
 'OH',
 'OH',
 'OH',
 'TX',
 'CO',
 'MI',
 'TX',
 'TX',
 'CA',
 'HI',
 'TX',
 'IN',
 'FL',
 'MO',
 'NV',
 'CA',
 'CA',
 'KY',
 'TN',
 'AZ',
 'FL',
 'WI',
 'MN',
 'TN',
 'LA',
 'NY',
 'NJ',
 'CA',
 'OK',
 'NE',
 'FL',
 'PA',
 'AZ',
 'PA',
 'OR',
 'NC',
 'CA',
 'UT',
 'TX',
 'CA',
 'CA',
 'CA',
 'WA',
 'MO',
 'FL',
 'AZ',
 'OK',
 'VA',
 'DC',
 'KS']

In [60]:
crime_report['state']= states

In [61]:
crime_report

,Unnamed: 0,Unnamed: 0.1,report_year,agency_code,agency_jurisdiction,population,violent_crimes,homicides,rapes,assaults,robberies,months_reported,crimes_percapita,homicides_percapita,rapes_percapita,assaults_percapita,robberies_percapita,state
0,0,2070,2005,NM00101,"Albuquerque, NM",490631,4670.0,53.0,285.0,3182.0,1150.0,12.0,951.84,10.80,58.09,648.55,234.39,NM
1,1,2071,2005,TX22001,"Arlington, TX",365380,2369.0,24.0,178.0,1399.0,768.0,12.0,648.37,6.57,48.72,382.89,210.19,TX
2,2,2072,2005,GAAPD00,"Atlanta, GA",430666,7213.0,90.0,223.0,4039.0,2861.0,12.0,1674.85,20.90,51.78,937.85,664.32,GA
3,3,2073,2005,CO00101,"Aurora, CO",295888,1835.0,28.0,223.0,940.0,644.0,12.0,620.17,9.46,75.37,317.69,217.65,CO
4,4,2074,2005,TX22701,"Austin, TX",693019,3393.0,26.0,312.0,1873.0,1182.0,12.0,489.60,3.75,45.02,270.27,170.56,TX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,753,2823,2015,AZ01003,"Tucson, AZ",529675,3472.0,31.0,422.0,1960.0,1059.0,NaN,655.50,5.85,79.67,370.04,199.93,AZ
744,754,2824,2015,OK07205,"Tulsa, OK",401520,3628.0,55.0,365.0,2354.0,854.0,NaN,903.57,13.70,90.90,586.27,212.69,OK
745,755,2825,2015,VA12800,"Virginia Beach, VA",452797,626.0,19.0,103.0,234.0,270.0,NaN,138.25,4.20,22.75,51.68,59.63,VA
746,756,2826,2015,DCMPD00,"Washington, DC",672228,8084.0,162.0,494.0,4024.0,3404.0,NaN,1202.57,24.10,73.49,598.61,506.38,DC
747,757,2827,2015,KS08703,"Wichita, KS",389824,3839.0,27.0,349.0,2730.0,733.0,NaN,984.80,6.93,89.53,700.32,188.03,KS

In [38]:
for i in range(0,len(list_of_cities)-1):
    
    crime_report['state'] = list_of_cities[i][len(list_of_cities[i]) - 2 : ]
crime_report

,Unnamed: 0,Unnamed: 0.1,report_year,agency_code,agency_jurisdiction,population,violent_crimes,homicides,rapes,assaults,robberies,months_reported,crimes_percapita,homicides_percapita,rapes_percapita,assaults_percapita,robberies_percapita,state
0,0,2070,2005,NM00101,"Albuquerque, NM",490631,4670.0,53.0,285.0,3182.0,1150.0,12.0,951.84,10.80,58.09,648.55,234.39,on
1,1,2071,2005,TX22001,"Arlington, TX",365380,2369.0,24.0,178.0,1399.0,768.0,12.0,648.37,6.57,48.72,382.89,210.19,on
2,2,2072,2005,GAAPD00,"Atlanta, GA",430666,7213.0,90.0,223.0,4039.0,2861.0,12.0,1674.85,20.90,51.78,937.85,664.32,on
3,3,2073,2005,CO00101,"Aurora, CO",295888,1835.0,28.0,223.0,940.0,644.0,12.0,620.17,9.46,75.37,317.69,217.65,on
4,4,2074,2005,TX22701,"Austin, TX",693019,3393.0,26.0,312.0,1873.0,1182.0,12.0,489.60,3.75,45.02,270.27,170.56,on
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,753,2823,2015,AZ01003,"Tucson, AZ",529675,3472.0,31.0,422.0,1960.0,1059.0,NaN,655.50,5.85,79.67,370.04,199.93,on
744,754,2824,2015,OK07205,"Tulsa, OK",401520,3628.0,55.0,365.0,2354.0,854.0,NaN,903.57,13.70,90.90,586.27,212.69,on
745,755,2825,2015,VA12800,"Virginia Beach, VA",452797,626.0,19.0,103.0,234.0,270.0,NaN,138.25,4.20,22.75,51.68,59.63,on
746,756,2826,2015,DCMPD00,"Washington, DC",672228,8084.0,162.0,494.0,4024.0,3404.0,NaN,1202.57,24.10,73.49,598.61,506.38,on
747,757,2827,2015,KS08703,"Wichita, KS",389824,3839.0,27.0,349.0,2730.0,733.0,NaN,984.80,6.93,89.53,700.32,188.03,on

In [34]:
for city in list_of_cities:
    for i in range(0, len(rent_2012)):
        if city in rent_2012['Areaname'].iloc[i]:
            print(rent_2012['Areaname'].iloc[i])

Albuquerque, NM MSA
Washington-Arlington-Alexandria, DC-VA-MD HUD Metro FMR Area
Fort Worth-Arlington, TX HUD Metro FMR Area
Atlanta-Sandy Springs-Marietta, GA HUD Metro FMR Area
Denver-Aurora-Broomfield, CO MSA
Austin-Round Rock-San Marcos, TX MSA
Baltimore-Towson, MD HUD Metro FMR Area
Boston-Cambridge-Quincy, MA-NH HUD Metro FMR Area
Buffalo-Niagara Falls, NY MSA
Charlotte-Gastonia-Rock Hill, NC-SC HUD Metro FMR Area
Charlottesville, VA MSA
Chicago-Joliet-Naperville, IL HUD Metro FMR Area
Cincinnati-Middleton, OH-KY-IN HUD Metro FMR Area
Cleveland-Elyria-Mentor, OH MSA
Cleveland, TN MSA
Columbus, GA-AL MSA
Columbus, IN MSA
Columbus, OH HUD Metro FMR Area
Dallas, TX HUD Metro FMR Area
Denver-Aurora-Broomfield, CO MSA
Detroit-Warren-Livonia, MI HUD Metro FMR Area
El Paso, TX MSA
Fort Worth-Arlington, TX HUD Metro FMR Area
Fresno, CA MSA
Honolulu, HI MSA
Houston-Baytown-Sugar Land, TX HUD Metro FMR Area
Indianapolis, IN HUD Metro FMR Area
Jacksonville, FL HUD Metro FMR Area
Jacksonville, NC MSA
Kansas City, MO-KS HUD Metro FMR Area
Las Vegas-Paradise, NV MSA
Los Angeles-Long Beach, CA HUD Metro FMR Area
Los Angeles-Long Beach, CA HUD Metro FMR Area
Louisville, KY-IN HUD Metro FMR Area
Memphis, TN-MS-AR HUD Metro FMR Area
Phoenix-Mesa-Glendale, AZ MSA
Miami-Miami Beach-Kendall, FL HUD Metro FMR Area
Milwaukee-Waukesha-West Allis, WI MSA
Minneapolis-St. Paul-Bloomington, MN-WI MSA
Nashville-Davidson--Murfreesboro--Franklin, TN MSA
New Orleans-Metairie-Kenner, LA MSA
New York, NY HUD Metro FMR Area
Newark, NJ HUD Metro FMR Area
Oakland-Fremont, CA HUD Metro FMR Area
Oklahoma City, OK HUD Metro FMR Area
Omaha-Council Bluffs, NE-IA HUD Metro FMR Area
Orlando-Kissimmee-Sanford, FL MSA
Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA
Phoenix-Mesa-Glendale, AZ MSA
Pittsburgh, PA HUD Metro FMR Area
Portland, ME HUD Metro FMR Area
Portland-Vancouver-Hillsboro, OR-WA MSA
Raleigh-Cary, NC MSA
Sacramento--Arden-Arcade--Roseville, CA HUD Metro FMR Area
Salt Lake City, UT HUD Metro FMR Area
San Antonio-New Braunfels, TX HUD Metro FMR Area
San Diego-Carlsbad-San Marcos, CA MSA
San Francisco, CA HUD Metro FMR Area
San Jose-Sunnyvale-Santa Clara, CA HUD Metro FMR Area
Seattle-Bellevue, WA HUD Metro FMR Area
St. Louis, MO-IL HUD Metro FMR Area
Tampa-St. Petersburg-Clearwater, FL MSA
Tucson, AZ MSA
Tulsa, OK HUD Metro FMR Area
Virginia Beach-Norfolk-Newport News, VA-NC MSA
Washington-Arlington-Alexandria, DC-VA-MD HUD Metro FMR Area
Wichita, KS HUD Metro FMR Area

In [62]:
crime_report.to_csv('Crime_with_states.csv')