In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('2010.csv')
df

,Label (Grouping),"Mesa city, Arizona!!Total!!Estimate","Mesa city, Arizona!!Male!!Estimate","Mesa city, Arizona!!Female!!Estimate","Phoenix city, Arizona!!Total!!Estimate","Phoenix city, Arizona!!Male!!Estimate","Phoenix city, Arizona!!Female!!Estimate","Tucson city, Arizona!!Total!!Estimate","Tucson city, Arizona!!Male!!Estimate","Tucson city, Arizona!!Female!!Estimate",...,"San Antonio city, Texas!!Female!!Estimate","Salt Lake City city, Utah!!Total!!Estimate","Salt Lake City city, Utah!!Male!!Estimate","Salt Lake City city, Utah!!Female!!Estimate","Seattle city, Washington!!Total!!Estimate","Seattle city, Washington!!Male!!Estimate","Seattle city, Washington!!Female!!Estimate","Milwaukee city, Wisconsin!!Total!!Estimate","Milwaukee city, Wisconsin!!Male!!Estimate","Milwaukee city, Wisconsin!!Female!!Estimate"
0,Population 18 to 24 years,"47,292","24,805","22,487","148,184","76,656","71,528","78,229","40,340","37,889",...,"75,951","24,999","11,340","13,659","71,575","33,897","37,678","80,625","40,096","40,529"
1,Less than high school graduate,20.4%,21.9%,18.8%,23.3%,26.1%,20.4%,15.4%,19.7%,10.8%,...,18.4%,12.1%,13.7%,10.8%,7.9%,8.6%,7.1%,18.8%,23.7%,14.0%
2,High school graduate (includes equivalency),26.9%,31.9%,21.4%,34.0%,36.5%,31.4%,26.0%,26.3%,25.7%,...,27.3%,19.1%,19.5%,18.7%,16.5%,16.8%,16.3%,24.7%,26.5%,23.0%
3,Some college or associate's degree,44.9%,42.7%,47.4%,37.9%,34.3%,41.8%,51.3%,46.9%,55.9%,...,48.0%,59.0%,59.9%,58.3%,53.8%,56.3%,51.5%,46.9%,42.1%,51.7%
4,Bachelor's degree or higher,7.7%,3.5%,12.4%,4.7%,3.1%,6.4%,7.3%,7.1%,7.6%,...,6.3%,9.8%,6.9%,12.2%,21.9%,18.3%,25.1%,9.5%,7.6%,11.3%
5,Population 25 years and over,"280,903","135,658","145,245","897,881","443,967","453,914","324,394","158,591","165,803",...,"434,296","116,013","57,381","58,632","443,842","220,565","223,277","356,525","166,893","189,632"
6,Less than 9th grade,6.0%,6.1%,6.0%,9.3%,9.2%,9.4%,7.2%,7.3%,7.1%,...,10.1%,5.6%,5.5%,5.8%,3.4%,3.0%,3.9%,6.9%,7.0%,6.7%
7,"9th to 12th grade, no diploma",7.3%,7.4%,7.3%,9.7%,10.2%,9.1%,8.6%,9.2%,7.9%,...,9.3%,10.9%,13.3%,8.5%,3.8%,4.6%,3.0%,12.5%,13.0%,12.0%
8,High school graduate (includes equivalency),28.0%,28.2%,27.8%,26.1%,26.2%,26.0%,24.0%,22.8%,25.1%,...,26.7%,17.4%,17.5%,17.3%,12.1%,12.5%,11.7%,31.8%,34.8%,29.2%
9,"Some college, no degree",27.5%,24.8%,30.0%,22.8%,21.8%,23.7%,27.2%,27.8%,26.6%,...,24.2%,22.0%,21.9%,22.1%,18.0%,18.9%,17.0%,21.5%,18.5%,24.2%
10,Associate's degree,8.8%,8.3%,9.2%,7.2%,7.4%,7.1%,7.8%,7.3%,8.2%,...,7.0%,6.8%,6.3%,7.2%,6.8%,6.4%,7.1%,5.9%,5.7%,6.1%
11,Bachelor's degree,15.0%,17.3%,12.9%,16.6%,16.8%,16.4%,15.2%,15.4%,15.0%,...,14.9%,21.4%,19.4%,23.4%,33.1%,31.6%,34.5%,13.9%,13.4%,14.3%
12,Graduate or professional degree,7.4%,8.0%,6.8%,8.3%,8.4%,8.2%,10.0%,10.1%,10.0%,...,7.9%,15.9%,16.1%,15.6%,22.9%,23.1%,22.8%,7.5%,7.6%,7.4%
13,Percent high school graduate or higher,86.7%,86.6%,86.8%,81.0%,80.6%,81.4%,84.2%,83.4%,85.0%,...,80.6%,83.5%,81.2%,85.7%,92.8%,92.5%,93.2%,80.6%,80.0%,81.2%
14,Percent bachelor's degree or higher,22.5%,25.4%,19.7%,24.9%,25.2%,24.7%,25.2%,25.5%,25.0%,...,22.8%,37.3%,35.4%,39.1%,56.0%,54.7%,57.3%,21.4%,21.0%,21.7%
15,Population 25 to 34 years,"61,051","33,206","27,845","232,274","118,987","113,287","77,505","39,041","38,464",...,"100,214","36,831","18,251","18,580","126,233","63,427","62,806","97,359","47,471","49,888"
16,High school graduate or higher,84.5%,82.4%,87.0%,79.6%,79.1%,80.2%,87.5%,86.9%,88.1%,...,87.9%,85.7%,83.0%,88.4%,95.7%,94.3%,97.1%,84.1%,82.0%,86.0%
17,Bachelor's degree or higher,22.2%,19.4%,25.5%,22.3%,20.1%,24.7%,26.3%,25.5%,27.1%,...,27.5%,36.9%,33.2%,40.5%,62.7%,57.8%,67.7%,27.6%,25.7%,29.4%
18,Population 35 to 44 years,"49,725","24,383","25,342","210,096","107,214","102,882","63,207","33,802","29,405",...,"87,765","24,527","13,050","11,477","99,512","52,266","47,246","73,149","35,025","38,124"
19,High school graduate or higher,85.0%,85.1%,84.9%,79.0%,78.6%,79.5%,83.3%,82.3%,84.5%,...,83.2%,81.0%,77.3%,85.2%,95.2%,95.2%,95.1%,80.2%,78.9%,81.4%
20,Bachelor's degree or higher,25.0%,27.3%,22.8%,25.9%,24.2%,27.7%,24.6%,21.3%,28.4%,...,25.7%,36.8%,37.0%,36.7%,63.1%,59.3%,67.4%,19.1%,19.5%,18.6%
21,Population 45 to 64 years,"105,500","51,260","54,240","329,095","160,899","168,196","121,402","57,614","63,788",...,"163,409","34,513","16,694","17,819","155,065","79,036","76,029","132,664","62,911","69,753"
22,High school graduate or higher,88.9%,88.9%,88.9%,83.6%,82.6%,84.5%,86.4%,85.6%,87.1%,...,83.3%,82.7%,82.5%,83.0%,92.5%,92.4%,92.7%,82.2%,82.3%,82.1%
23,Bachelor's degree or higher,24.3%,26.9%,21.8%,27.5%,28.9%,26.1%,26.1%,26.5%,25.7%,...,22.4%,39.9%,31.2%,48.1%,52.9%,51.9%,54.0%,20.3%,18.9%,21.6%
24,Population 65 years and over,"64,627","26,809","37,818","126,416","56,867","69,549","62,280","28,134","34,146",...,"82,908","20,142","9,386","10,756","63,032","25,836","37,196","53,353","21,486","31,867"
25,High school graduate or higher,86.4%,88.7%,84.8%,80.2%,81.7%,78.9%,76.9%,75.6%,77.9%,...,63.9%,83.6%,80.8%,86.0%,84.1%,82.8%,85.0%,71.1%,70.5%,71.5%
26,Bachelor's degree or higher,17.7%,27.9%,10.5%,21.4%,27.4%,16.5%,22.8%,28.4%,18.2%,...,15.0%,34.1%,45.3%,24.3%,38.6%,46.0%,33.5%,15.7%,19.2%,13.4%
27,POVERTY RATE FOR THE POPULATION 25 YEARS AND O...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Less than high school graduate,22.2%,20.2%,24.0%,36.2%,36.1%,36.3%,31.0%,30.5%,31.6%,...,34.8%,33.5%,31.0%,36.6%,29.2%,28.7%,29.8%,35.4%,29.4%,41.1%
29,High school graduate (includes equivalency),10.8%,10.4%,11.2%,22.2%,21.3%,23.2%,20.9%,18.7%,22.7%,...,17.4%,22.0%,25.2%,18.9%,21.0%,24.5%,17.3%,22.5%,22.5%,22.5%
30,Some college or associate's degree,9.2%,7.5%,10.5%,12.4%,9.7%,14.8%,17.0%,16.0%,18.0%,...,12.0%,14.5%,14.1%,14.8%,13.1%,13.2%,13.0%,17.7%,13.5%,20.6%
31,Bachelor's degree or higher,4.4%,3.9%,5.1%,4.7%,3.8%,5.6%,6.1%,5.8%,6.4%,...,4.9%,8.4%,10.9%,6.1%,5.9%,6.0%,5.8%,5.5%,5.7%,5.4%
32,MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2010...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Population 25 years and over with earnings,"31,165","35,082","27,267","32,058","34,995","30,422","26,845","30,497","24,170",...,"26,843","26,530","28,422","25,496","42,067","49,452","36,958","27,676","30,244","26,074"
34,Less than high school graduate,"16,942","17,914","15,584","18,374","20,637","15,355","16,628","19,098","14,151",...,"15,537","19,407","20,057","18,122","21,457","22,882","20,287","17,610","20,732","13,071"
35,High school graduate (includes equivalency),"26,196","29,897","23,025","24,837","26,784","22,492","22,249","23,940","21,612",...,"20,928","20,584","20,962","19,952","27,419","30,627","25,227","24,337","25,966","22,684"
36,Some college or associate's degree,"31,249","36,680","27,311","32,294","36,299","30,102","26,727","30,696","23,391",...,"26,988","24,169","25,315","22,258","31,819","36,590","28,481","26,973","30,385","25,333"
37,Bachelor's degree,"43,655","50,482","36,667","50,441","60,051","42,983","38,089","43,013","31,735",...,"42,807","35,431","41,765","29,776","48,977","56,100","41,515","40,611","43,668","36,832"
38,Graduate or professional degree,"61,242","78,075","52,467","64,637","75,847","56,234","45,745","46,897","43,909",...,"52,058","52,414","61,181","51,608","61,988","76,926","53,931","52,989","57,139","51,451"
39,PERCENT IMPUTED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Educational attainment,8.5%,(X),(X),8.9%,(X),(X),5.8%,(X),(X),...,(X),2.0%,(X),(X),4.2%,(X),(X),5.8%,(X),(X)

In [6]:
df = df[df.columns.drop(list(df.filter(regex='Male')))]
df = df[df.columns.drop(list(df.filter(regex='Female')))]
df

,Label (Grouping),"Mesa city, Arizona!!Total!!Estimate","Phoenix city, Arizona!!Total!!Estimate","Tucson city, Arizona!!Total!!Estimate","Fresno city, California!!Total!!Estimate","Los Angeles city, California!!Total!!Estimate","Oakland city, California!!Total!!Estimate","Sacramento city, California!!Total!!Estimate","San Diego city, California!!Total!!Estimate","San Francisco city, California!!Total!!Estimate",...,"Arlington city, Texas!!Total!!Estimate","Austin city, Texas!!Total!!Estimate","Dallas city, Texas!!Total!!Estimate","El Paso city, Texas!!Total!!Estimate","Fort Worth city, Texas!!Total!!Estimate","Houston city, Texas!!Total!!Estimate","San Antonio city, Texas!!Total!!Estimate","Salt Lake City city, Utah!!Total!!Estimate","Seattle city, Washington!!Total!!Estimate","Milwaukee city, Wisconsin!!Total!!Estimate"
0,Population 18 to 24 years,"47,292","148,184","78,229","60,911","433,064","34,889","51,146","176,827","77,868",...,"42,429","114,518","126,382","73,538","75,354","227,777","152,095","24,999","71,575","80,625"
1,Less than high school graduate,20.4%,23.3%,15.4%,23.5%,20.4%,21.4%,20.5%,8.6%,10.1%,...,19.7%,14.3%,29.4%,16.8%,19.8%,23.6%,19.9%,12.1%,7.9%,18.8%
2,High school graduate (includes equivalency),26.9%,34.0%,26.0%,24.5%,23.8%,25.8%,26.1%,23.7%,20.3%,...,29.2%,21.7%,26.2%,32.1%,30.9%,28.7%,30.8%,19.1%,16.5%,24.7%
3,Some college or associate's degree,44.9%,37.9%,51.3%,47.0%,45.3%,41.6%,44.5%,55.0%,44.7%,...,42.0%,50.6%,33.2%,45.9%,40.5%,37.1%,44.3%,59.0%,53.8%,46.9%
4,Bachelor's degree or higher,7.7%,4.7%,7.3%,5.0%,10.5%,11.2%,9.0%,12.6%,24.9%,...,9.1%,13.4%,11.2%,5.2%,8.9%,10.6%,5.0%,9.8%,21.9%,9.5%
5,Population 25 years and over,"280,903","897,881","324,394","282,811","2,481,239","271,827","300,055","846,292","620,010",...,"222,302","502,032","759,848","392,821","453,331","1,337,138","826,467","116,013","443,842","356,525"
6,Less than 9th grade,6.0%,9.3%,7.2%,14.9%,16.1%,11.8%,8.8%,6.6%,8.5%,...,7.6%,8.2%,14.6%,14.5%,10.3%,14.4%,10.1%,5.6%,3.4%,6.9%
7,"9th to 12th grade, no diploma",7.3%,9.7%,8.6%,10.6%,10.0%,8.3%,9.5%,6.4%,5.6%,...,8.9%,6.2%,11.9%,10.1%,9.8%,11.3%,9.7%,10.9%,3.8%,12.5%
8,High school graduate (includes equivalency),28.0%,26.1%,24.0%,22.7%,19.1%,16.9%,20.7%,16.4%,14.2%,...,24.4%,17.3%,22.8%,24.2%,24.4%,22.1%,25.6%,17.4%,12.1%,31.8%
9,"Some college, no degree",27.5%,22.8%,27.2%,23.1%,18.3%,20.0%,25.0%,22.0%,15.6%,...,24.5%,19.3%,17.8%,23.3%,23.0%,19.5%,23.9%,22.0%,18.0%,21.5%
10,Associate's degree,8.8%,7.2%,7.8%,8.7%,5.8%,5.5%,7.8%,8.2%,5.3%,...,7.1%,5.3%,4.0%,6.4%,6.4%,4.5%,6.9%,6.8%,6.8%,5.9%
11,Bachelor's degree,15.0%,16.6%,15.2%,13.9%,20.4%,21.5%,18.1%,24.1%,31.4%,...,19.1%,27.5%,18.5%,14.2%,18.5%,17.4%,15.0%,21.4%,33.1%,13.9%
12,Graduate or professional degree,7.4%,8.3%,10.0%,6.2%,10.3%,15.9%,10.1%,16.3%,19.5%,...,8.3%,16.1%,10.4%,7.3%,7.5%,11.0%,8.8%,15.9%,22.9%,7.5%
13,Percent high school graduate or higher,86.7%,81.0%,84.2%,74.6%,73.9%,79.9%,81.7%,86.9%,85.9%,...,83.5%,85.6%,73.5%,75.4%,79.9%,74.3%,80.2%,83.5%,92.8%,80.6%
14,Percent bachelor's degree or higher,22.5%,24.9%,25.2%,20.1%,30.7%,37.4%,28.1%,40.3%,50.9%,...,27.5%,43.7%,28.9%,21.5%,26.1%,28.3%,23.7%,37.3%,56.0%,21.4%
15,Population 25 to 34 years,"61,051","232,274","77,505","77,799","641,454","65,305","78,527","225,296","167,944",...,"54,059","162,247","223,937","85,613","121,017","371,133","200,645","36,831","126,233","97,359"
16,High school graduate or higher,84.5%,79.6%,87.5%,79.3%,79.5%,83.8%,87.0%,92.0%,95.9%,...,84.9%,86.6%,73.8%,85.0%,82.9%,75.3%,85.5%,85.7%,95.7%,84.1%
17,Bachelor's degree or higher,22.2%,22.3%,26.3%,19.3%,35.0%,40.8%,33.2%,44.6%,71.1%,...,24.6%,44.4%,29.0%,22.0%,27.8%,29.9%,25.5%,36.9%,62.7%,27.6%
18,Population 35 to 44 years,"49,725","210,096","63,207","59,875","565,451","64,385","60,995","184,449","134,797",...,"52,065","118,497","167,406","84,471","108,355","296,571","171,498","24,527","99,512","73,149"
19,High school graduate or higher,85.0%,79.0%,83.3%,74.1%,73.2%,82.9%,82.9%,85.8%,91.5%,...,77.4%,84.9%,70.5%,83.9%,79.3%,72.9%,82.8%,81.0%,95.2%,80.2%
20,Bachelor's degree or higher,25.0%,25.9%,24.6%,23.5%,31.6%,44.1%,28.4%,39.3%,60.2%,...,22.9%,45.9%,26.1%,26.8%,26.7%,27.4%,24.5%,36.8%,63.1%,19.1%
21,Population 45 to 64 years,"105,500","329,095","121,402","100,378","880,221","95,978","109,525","299,087","206,928",...,"86,722","165,063","259,312","148,971","163,790","476,352","312,393","34,513","155,065","132,664"
22,High school graduate or higher,88.9%,83.6%,86.4%,73.8%,72.1%,79.2%,82.6%,87.5%,82.6%,...,86.9%,86.7%,74.5%,76.8%,80.6%,75.6%,81.3%,82.7%,92.5%,82.2%
23,Bachelor's degree or higher,24.3%,27.5%,26.1%,20.1%,29.0%,33.9%,26.6%,40.8%,39.5%,...,32.2%,44.7%,29.8%,22.5%,25.8%,28.7%,24.0%,39.9%,52.9%,20.3%
24,Population 65 years and over,"64,627","126,416","62,280","44,759","394,113","46,159","51,008","137,460","110,341",...,"29,456","56,225","109,193","73,766","60,169","193,082","141,931","20,142","63,032","53,353"
25,High school graduate or higher,86.4%,80.2%,76.9%,68.7%,69.8%,71.6%,70.1%,78.9%,70.2%,...,81.6%,80.6%,75.0%,51.6%,72.7%,71.4%,67.1%,83.6%,84.1%,71.1%
26,Bachelor's degree or higher,17.7%,21.4%,22.8%,16.7%,26.1%,30.7%,23.2%,33.7%,29.9%,...,26.8%,34.0%,30.9%,12.9%,22.0%,25.7%,19.7%,34.1%,38.6%,15.7%
27,POVERTY RATE FOR THE POPULATION 25 YEARS AND O...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Less than high school graduate,22.2%,36.2%,31.0%,41.1%,30.0%,33.2%,30.3%,31.4%,20.4%,...,21.3%,37.4%,30.0%,32.0%,25.6%,31.7%,28.8%,33.5%,29.2%,35.4%
29,High school graduate (includes equivalency),10.8%,22.2%,20.9%,23.9%,19.7%,24.2%,21.9%,18.4%,15.9%,...,13.1%,18.8%,22.2%,17.3%,17.5%,20.0%,15.9%,22.0%,21.0%,22.5%
30,Some college or associate's degree,9.2%,12.4%,17.0%,15.8%,13.6%,16.8%,13.1%,11.4%,12.4%,...,7.1%,11.7%,12.9%,12.7%,10.3%,14.1%,10.4%,14.5%,13.1%,17.7%
31,Bachelor's degree or higher,4.4%,4.7%,6.1%,5.5%,7.3%,6.4%,6.2%,5.2%,6.3%,...,3.5%,6.0%,4.7%,4.7%,4.6%,5.5%,5.2%,8.4%,5.9%,5.5%
32,MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2010...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Population 25 years and over with earnings,"31,165","32,058","26,845","26,413","30,072","35,437","35,155","40,069","46,987",...,"31,777","33,102","29,273","25,829","32,266","30,241","29,783","26,530","42,067","27,676"
34,Less than high school graduate,"16,942","18,374","16,628","14,035","16,264","16,981","17,558","17,004","19,781",...,"19,121","16,758","17,505","14,797","18,913","17,338","18,379","19,407","21,457","17,610"
35,High school graduate (includes equivalency),"26,196","24,837","22,249","21,675","23,224","21,465","26,661","26,068","26,295",...,"25,095","22,495","23,264","20,689","28,546","23,406","23,395","20,584","27,419","24,337"
36,Some college or associate's degree,"31,249","32,294","26,727","28,772","31,582","34,838","32,634","35,081","37,522",...,"31,384","30,731","30,796","27,503","32,250","30,313","30,360","24,169","31,819","26,973"
37,Bachelor's degree,"43,655","50,441","38,089","45,342","46,188","47,629","48,869","52,004","60,073",...,"47,763","46,491","50,308","42,813","50,892","50,495","46,169","35,431","48,977","40,611"
38,Graduate or professional degree,"61,242","64,637","45,745","57,999","65,639","70,456","62,095","71,934","80,370",...,"61,091","60,571","70,596","56,902","63,140","67,082","61,019","52,414","61,988","52,989"
39,PERCENT IMPUTED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Educational attainment,8.5%,8.9%,5.8%,8.8%,7.3%,6.9%,5.1%,5.0%,6.7%,...,4.6%,5.4%,6.5%,3.5%,3.8%,5.9%,4.9%,2.0%,4.2%,5.8%

In [8]:
df1=df.drop(df.index[16:27])

In [9]:
df1

,Label (Grouping),"Mesa city, Arizona!!Total!!Estimate","Phoenix city, Arizona!!Total!!Estimate","Tucson city, Arizona!!Total!!Estimate","Fresno city, California!!Total!!Estimate","Los Angeles city, California!!Total!!Estimate","Oakland city, California!!Total!!Estimate","Sacramento city, California!!Total!!Estimate","San Diego city, California!!Total!!Estimate","San Francisco city, California!!Total!!Estimate",...,"Arlington city, Texas!!Total!!Estimate","Austin city, Texas!!Total!!Estimate","Dallas city, Texas!!Total!!Estimate","El Paso city, Texas!!Total!!Estimate","Fort Worth city, Texas!!Total!!Estimate","Houston city, Texas!!Total!!Estimate","San Antonio city, Texas!!Total!!Estimate","Salt Lake City city, Utah!!Total!!Estimate","Seattle city, Washington!!Total!!Estimate","Milwaukee city, Wisconsin!!Total!!Estimate"
0,Population 18 to 24 years,"47,292","148,184","78,229","60,911","433,064","34,889","51,146","176,827","77,868",...,"42,429","114,518","126,382","73,538","75,354","227,777","152,095","24,999","71,575","80,625"
1,Less than high school graduate,20.4%,23.3%,15.4%,23.5%,20.4%,21.4%,20.5%,8.6%,10.1%,...,19.7%,14.3%,29.4%,16.8%,19.8%,23.6%,19.9%,12.1%,7.9%,18.8%
2,High school graduate (includes equivalency),26.9%,34.0%,26.0%,24.5%,23.8%,25.8%,26.1%,23.7%,20.3%,...,29.2%,21.7%,26.2%,32.1%,30.9%,28.7%,30.8%,19.1%,16.5%,24.7%
3,Some college or associate's degree,44.9%,37.9%,51.3%,47.0%,45.3%,41.6%,44.5%,55.0%,44.7%,...,42.0%,50.6%,33.2%,45.9%,40.5%,37.1%,44.3%,59.0%,53.8%,46.9%
4,Bachelor's degree or higher,7.7%,4.7%,7.3%,5.0%,10.5%,11.2%,9.0%,12.6%,24.9%,...,9.1%,13.4%,11.2%,5.2%,8.9%,10.6%,5.0%,9.8%,21.9%,9.5%
5,Population 25 years and over,"280,903","897,881","324,394","282,811","2,481,239","271,827","300,055","846,292","620,010",...,"222,302","502,032","759,848","392,821","453,331","1,337,138","826,467","116,013","443,842","356,525"
6,Less than 9th grade,6.0%,9.3%,7.2%,14.9%,16.1%,11.8%,8.8%,6.6%,8.5%,...,7.6%,8.2%,14.6%,14.5%,10.3%,14.4%,10.1%,5.6%,3.4%,6.9%
7,"9th to 12th grade, no diploma",7.3%,9.7%,8.6%,10.6%,10.0%,8.3%,9.5%,6.4%,5.6%,...,8.9%,6.2%,11.9%,10.1%,9.8%,11.3%,9.7%,10.9%,3.8%,12.5%
8,High school graduate (includes equivalency),28.0%,26.1%,24.0%,22.7%,19.1%,16.9%,20.7%,16.4%,14.2%,...,24.4%,17.3%,22.8%,24.2%,24.4%,22.1%,25.6%,17.4%,12.1%,31.8%
9,"Some college, no degree",27.5%,22.8%,27.2%,23.1%,18.3%,20.0%,25.0%,22.0%,15.6%,...,24.5%,19.3%,17.8%,23.3%,23.0%,19.5%,23.9%,22.0%,18.0%,21.5%
10,Associate's degree,8.8%,7.2%,7.8%,8.7%,5.8%,5.5%,7.8%,8.2%,5.3%,...,7.1%,5.3%,4.0%,6.4%,6.4%,4.5%,6.9%,6.8%,6.8%,5.9%
11,Bachelor's degree,15.0%,16.6%,15.2%,13.9%,20.4%,21.5%,18.1%,24.1%,31.4%,...,19.1%,27.5%,18.5%,14.2%,18.5%,17.4%,15.0%,21.4%,33.1%,13.9%
12,Graduate or professional degree,7.4%,8.3%,10.0%,6.2%,10.3%,15.9%,10.1%,16.3%,19.5%,...,8.3%,16.1%,10.4%,7.3%,7.5%,11.0%,8.8%,15.9%,22.9%,7.5%
13,Percent high school graduate or higher,86.7%,81.0%,84.2%,74.6%,73.9%,79.9%,81.7%,86.9%,85.9%,...,83.5%,85.6%,73.5%,75.4%,79.9%,74.3%,80.2%,83.5%,92.8%,80.6%
14,Percent bachelor's degree or higher,22.5%,24.9%,25.2%,20.1%,30.7%,37.4%,28.1%,40.3%,50.9%,...,27.5%,43.7%,28.9%,21.5%,26.1%,28.3%,23.7%,37.3%,56.0%,21.4%
15,Population 25 to 34 years,"61,051","232,274","77,505","77,799","641,454","65,305","78,527","225,296","167,944",...,"54,059","162,247","223,937","85,613","121,017","371,133","200,645","36,831","126,233","97,359"
27,POVERTY RATE FOR THE POPULATION 25 YEARS AND O...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Less than high school graduate,22.2%,36.2%,31.0%,41.1%,30.0%,33.2%,30.3%,31.4%,20.4%,...,21.3%,37.4%,30.0%,32.0%,25.6%,31.7%,28.8%,33.5%,29.2%,35.4%
29,High school graduate (includes equivalency),10.8%,22.2%,20.9%,23.9%,19.7%,24.2%,21.9%,18.4%,15.9%,...,13.1%,18.8%,22.2%,17.3%,17.5%,20.0%,15.9%,22.0%,21.0%,22.5%
30,Some college or associate's degree,9.2%,12.4%,17.0%,15.8%,13.6%,16.8%,13.1%,11.4%,12.4%,...,7.1%,11.7%,12.9%,12.7%,10.3%,14.1%,10.4%,14.5%,13.1%,17.7%
31,Bachelor's degree or higher,4.4%,4.7%,6.1%,5.5%,7.3%,6.4%,6.2%,5.2%,6.3%,...,3.5%,6.0%,4.7%,4.7%,4.6%,5.5%,5.2%,8.4%,5.9%,5.5%
32,MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2010...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Population 25 years and over with earnings,"31,165","32,058","26,845","26,413","30,072","35,437","35,155","40,069","46,987",...,"31,777","33,102","29,273","25,829","32,266","30,241","29,783","26,530","42,067","27,676"
34,Less than high school graduate,"16,942","18,374","16,628","14,035","16,264","16,981","17,558","17,004","19,781",...,"19,121","16,758","17,505","14,797","18,913","17,338","18,379","19,407","21,457","17,610"
35,High school graduate (includes equivalency),"26,196","24,837","22,249","21,675","23,224","21,465","26,661","26,068","26,295",...,"25,095","22,495","23,264","20,689","28,546","23,406","23,395","20,584","27,419","24,337"
36,Some college or associate's degree,"31,249","32,294","26,727","28,772","31,582","34,838","32,634","35,081","37,522",...,"31,384","30,731","30,796","27,503","32,250","30,313","30,360","24,169","31,819","26,973"
37,Bachelor's degree,"43,655","50,441","38,089","45,342","46,188","47,629","48,869","52,004","60,073",...,"47,763","46,491","50,308","42,813","50,892","50,495","46,169","35,431","48,977","40,611"
38,Graduate or professional degree,"61,242","64,637","45,745","57,999","65,639","70,456","62,095","71,934","80,370",...,"61,091","60,571","70,596","56,902","63,140","67,082","61,019","52,414","61,988","52,989"
39,PERCENT IMPUTED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Educational attainment,8.5%,8.9%,5.8%,8.8%,7.3%,6.9%,5.1%,5.0%,6.7%,...,4.6%,5.4%,6.5%,3.5%,3.8%,5.9%,4.9%,2.0%,4.2%,5.8%

In [10]:
df1=df1.drop(df.index[15])
df1

,Label (Grouping),"Mesa city, Arizona!!Total!!Estimate","Phoenix city, Arizona!!Total!!Estimate","Tucson city, Arizona!!Total!!Estimate","Fresno city, California!!Total!!Estimate","Los Angeles city, California!!Total!!Estimate","Oakland city, California!!Total!!Estimate","Sacramento city, California!!Total!!Estimate","San Diego city, California!!Total!!Estimate","San Francisco city, California!!Total!!Estimate",...,"Arlington city, Texas!!Total!!Estimate","Austin city, Texas!!Total!!Estimate","Dallas city, Texas!!Total!!Estimate","El Paso city, Texas!!Total!!Estimate","Fort Worth city, Texas!!Total!!Estimate","Houston city, Texas!!Total!!Estimate","San Antonio city, Texas!!Total!!Estimate","Salt Lake City city, Utah!!Total!!Estimate","Seattle city, Washington!!Total!!Estimate","Milwaukee city, Wisconsin!!Total!!Estimate"
0,Population 18 to 24 years,"47,292","148,184","78,229","60,911","433,064","34,889","51,146","176,827","77,868",...,"42,429","114,518","126,382","73,538","75,354","227,777","152,095","24,999","71,575","80,625"
1,Less than high school graduate,20.4%,23.3%,15.4%,23.5%,20.4%,21.4%,20.5%,8.6%,10.1%,...,19.7%,14.3%,29.4%,16.8%,19.8%,23.6%,19.9%,12.1%,7.9%,18.8%
2,High school graduate (includes equivalency),26.9%,34.0%,26.0%,24.5%,23.8%,25.8%,26.1%,23.7%,20.3%,...,29.2%,21.7%,26.2%,32.1%,30.9%,28.7%,30.8%,19.1%,16.5%,24.7%
3,Some college or associate's degree,44.9%,37.9%,51.3%,47.0%,45.3%,41.6%,44.5%,55.0%,44.7%,...,42.0%,50.6%,33.2%,45.9%,40.5%,37.1%,44.3%,59.0%,53.8%,46.9%
4,Bachelor's degree or higher,7.7%,4.7%,7.3%,5.0%,10.5%,11.2%,9.0%,12.6%,24.9%,...,9.1%,13.4%,11.2%,5.2%,8.9%,10.6%,5.0%,9.8%,21.9%,9.5%
5,Population 25 years and over,"280,903","897,881","324,394","282,811","2,481,239","271,827","300,055","846,292","620,010",...,"222,302","502,032","759,848","392,821","453,331","1,337,138","826,467","116,013","443,842","356,525"
6,Less than 9th grade,6.0%,9.3%,7.2%,14.9%,16.1%,11.8%,8.8%,6.6%,8.5%,...,7.6%,8.2%,14.6%,14.5%,10.3%,14.4%,10.1%,5.6%,3.4%,6.9%
7,"9th to 12th grade, no diploma",7.3%,9.7%,8.6%,10.6%,10.0%,8.3%,9.5%,6.4%,5.6%,...,8.9%,6.2%,11.9%,10.1%,9.8%,11.3%,9.7%,10.9%,3.8%,12.5%
8,High school graduate (includes equivalency),28.0%,26.1%,24.0%,22.7%,19.1%,16.9%,20.7%,16.4%,14.2%,...,24.4%,17.3%,22.8%,24.2%,24.4%,22.1%,25.6%,17.4%,12.1%,31.8%
9,"Some college, no degree",27.5%,22.8%,27.2%,23.1%,18.3%,20.0%,25.0%,22.0%,15.6%,...,24.5%,19.3%,17.8%,23.3%,23.0%,19.5%,23.9%,22.0%,18.0%,21.5%
10,Associate's degree,8.8%,7.2%,7.8%,8.7%,5.8%,5.5%,7.8%,8.2%,5.3%,...,7.1%,5.3%,4.0%,6.4%,6.4%,4.5%,6.9%,6.8%,6.8%,5.9%
11,Bachelor's degree,15.0%,16.6%,15.2%,13.9%,20.4%,21.5%,18.1%,24.1%,31.4%,...,19.1%,27.5%,18.5%,14.2%,18.5%,17.4%,15.0%,21.4%,33.1%,13.9%
12,Graduate or professional degree,7.4%,8.3%,10.0%,6.2%,10.3%,15.9%,10.1%,16.3%,19.5%,...,8.3%,16.1%,10.4%,7.3%,7.5%,11.0%,8.8%,15.9%,22.9%,7.5%
13,Percent high school graduate or higher,86.7%,81.0%,84.2%,74.6%,73.9%,79.9%,81.7%,86.9%,85.9%,...,83.5%,85.6%,73.5%,75.4%,79.9%,74.3%,80.2%,83.5%,92.8%,80.6%
14,Percent bachelor's degree or higher,22.5%,24.9%,25.2%,20.1%,30.7%,37.4%,28.1%,40.3%,50.9%,...,27.5%,43.7%,28.9%,21.5%,26.1%,28.3%,23.7%,37.3%,56.0%,21.4%
27,POVERTY RATE FOR THE POPULATION 25 YEARS AND O...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Less than high school graduate,22.2%,36.2%,31.0%,41.1%,30.0%,33.2%,30.3%,31.4%,20.4%,...,21.3%,37.4%,30.0%,32.0%,25.6%,31.7%,28.8%,33.5%,29.2%,35.4%
29,High school graduate (includes equivalency),10.8%,22.2%,20.9%,23.9%,19.7%,24.2%,21.9%,18.4%,15.9%,...,13.1%,18.8%,22.2%,17.3%,17.5%,20.0%,15.9%,22.0%,21.0%,22.5%
30,Some college or associate's degree,9.2%,12.4%,17.0%,15.8%,13.6%,16.8%,13.1%,11.4%,12.4%,...,7.1%,11.7%,12.9%,12.7%,10.3%,14.1%,10.4%,14.5%,13.1%,17.7%
31,Bachelor's degree or higher,4.4%,4.7%,6.1%,5.5%,7.3%,6.4%,6.2%,5.2%,6.3%,...,3.5%,6.0%,4.7%,4.7%,4.6%,5.5%,5.2%,8.4%,5.9%,5.5%
32,MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2010...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Population 25 years and over with earnings,"31,165","32,058","26,845","26,413","30,072","35,437","35,155","40,069","46,987",...,"31,777","33,102","29,273","25,829","32,266","30,241","29,783","26,530","42,067","27,676"
34,Less than high school graduate,"16,942","18,374","16,628","14,035","16,264","16,981","17,558","17,004","19,781",...,"19,121","16,758","17,505","14,797","18,913","17,338","18,379","19,407","21,457","17,610"
35,High school graduate (includes equivalency),"26,196","24,837","22,249","21,675","23,224","21,465","26,661","26,068","26,295",...,"25,095","22,495","23,264","20,689","28,546","23,406","23,395","20,584","27,419","24,337"
36,Some college or associate's degree,"31,249","32,294","26,727","28,772","31,582","34,838","32,634","35,081","37,522",...,"31,384","30,731","30,796","27,503","32,250","30,313","30,360","24,169","31,819","26,973"
37,Bachelor's degree,"43,655","50,441","38,089","45,342","46,188","47,629","48,869","52,004","60,073",...,"47,763","46,491","50,308","42,813","50,892","50,495","46,169","35,431","48,977","40,611"
38,Graduate or professional degree,"61,242","64,637","45,745","57,999","65,639","70,456","62,095","71,934","80,370",...,"61,091","60,571","70,596","56,902","63,140","67,082","61,019","52,414","61,988","52,989"
39,PERCENT IMPUTED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Educational attainment,8.5%,8.9%,5.8%,8.8%,7.3%,6.9%,5.1%,5.0%,6.7%,...,4.6%,5.4%,6.5%,3.5%,3.8%,5.9%,4.9%,2.0%,4.2%,5.8%

In [11]:
df1.to_csv('clean2010.csv')